config/routes.rb
Rails.application.routes.draw do

  resources :tags

  resources :repbodies, :only=> %w[show index opinion destroy]

  resources :roles

  resources :users do
    resources :fileupload, :only => %w[index]
    resources :repbodies do #, :except => %w[new create destroy]
      resources :comments do
        resources :usercomments
      end
    end
  end
  resources :users#, :only => %w[indexyear] #, :except => %w[new create destroy update edit]

  resources :sessions 
  get "login" => "sessions#new", :as => "login" 
  get "logout" => "sessions#destroy", :as => "logout" 
  get "userapplicate" => "users#newext", :as => "userapplicate" 
  post "createext" => "users#createext", :as => "createext" , :via => "get"
  post "indexyear" => "users#indexyear", :as => "indexyear" , :via => "get"
  post "upload_process" => "fileupload#upload_process", :as => "upload_process" , :via => "get"
  post "repbodies" => "repbodies#index",  :via => "get"
  post "indexyeartag" => "repbodies#indexyeartag", :as => "indexyeartag", :via => "get"
  match '/acception/:id' => 'users#acception', :as => "acception", :via => "get"
  match '/mypage/:id' => 'users#mypage', :as => "mypage", :via => "get"
  match '/chpass/:id' => 'users#chpass', :as => "chpass", :via => "get"
  match '/userreportshow/:id' => 'users#userreportshow', :as => "userreportshow", :via => "get"
  match '/opinion/' => 'repbodies#opinion', :as => "opinion", :via => "get"
  match '/fileupload/' =>  'fileupload#upload', :via => "get"
  match '/years/' =>  'years#index', :via => [:get, :post]
  match '/avatar/:id' =>  'users#avatar',  :as => "avatar", :via => "get"
  match 'indexyear' => 'users#indexyear',  :via => "get"
  match 'indexyeartag' => 'repbodies#indexyeartag', :via => "get"

  match ':controller(/:action(/:id))(.:format)', :via => "get"
  root :to => 'showindex#index'
end

app/models/user.rb
# -*- coding: utf-8 -*-
class User < ActiveRecord::Base
#  attr_accessible :account, :email, :grade, :password_digest, :role_id, :studentid, :username
#  attr_accessible :account, :email, :grade, :password, :role_id, :studentid, :username, :password_confirmation, :machine, :acception, :owner, :year, :furigana #, :password_digest
  mount_uploader :avatar, AvatarUploader
  belongs_to :role
  has_many :repbodies
  has_many :myfiles
  has_many :comments, :through => :repbodies
  has_many :usercomments, :through => :repbodies, :through => :comments
#=begin
  has_secure_password 
  validates_presence_of :password, :on => :create 
  validates :account, :presence => true, 
                      :uniqueness => true, 
                      :format => { :with => /(\w|\d)+/,
                                   :message => "は半角英数字で記入して下さい" }, 
                      :on => :create
  validates :username, :presence => true, :on => :create
  validates :furigana, :presence => true, :on => :create
  validates :role_id, :presence => true, :numericality => true, :on => :create
  validates :studentid, :presence => true, :numericality => true, :on => :create
  validates :grade, :presence => true,  
            :format => { :with => /\A[A-Z]\d\z/,
                         :message => "は '大文字アルファベット + 数字' で記入してください"
                       },
            :on => :create
  validates :machine, :presence => true,  
            :format => { :with => /\Ajoho[0-9][0-9]\z/,
                         :message => "は 'johoXX'(XX は 2 桁の数字) で記入してください"
                       },
            :on => :create
  validates :email, :presence => true,  
            :uniqueness => true, 
            :format => { :with => /\A\S*\S@\S*/,
                         :message => "がまちがっています．確認してください. "
                       },
            :on => :create
  validates :owner, :presence => true, 
	    if: :check_owner,
            :format => { :with => /(\w|\d)+/,
                         :message => "が間違っています．半角英数字で記入してください. "
                       },
            :on => :create
#=end
private
def check_owner
    if User.exists?(account: owner) 
     @ownerid = User.where(account: owner).pluck(:role_id)
       if @ownerid == [4]
	  errors.add(:owner, "にはTA, VTA, Staff のアカウントを入力してください")
       else
       end
    else 
	  errors.add(:owner, "にはTA, VTA, Staff のアカウントを正確に入力してください")      
    end
  end
def user_params
#    params.require(:user).permit(:account, :email, :grade, :password_digest, :role_id, :studentid, :username, :password_confirmation, :machine, :acception, :owner, :year, :furigana, :password_digest)
    params.require(:user).permit(:account, :email, :grade, :password_digest, :role_id, :studentid, :username, :password_confirmation, :machine, :acception, :owner, :year, :furigana)
end
end

app/controllers/users_controller.rb
# -*- coding: utf-8 -*-
class UsersController < ApplicationController
  skip_before_filter :check_logined, :only => ['newext', 'createext']
  before_filter :edit_check, :only => ['new', 'create', 'edit', 'destroy', 'acception']
  before_filter :mypage_check, :only => ['mypage', 'chpass', 'show']

  # GET /users
  # GET /users.json
  def index
    @thisyear = Year.find_by(default: 't')
    @yearserch = params[:yearserch].to_i
#    @years = Year.all
    @years = Year.order("year DESC")
    @year_name = Array.new
    @years.each do |year|
      @year_name[year.id.to_i] = year.year.to_s
    end
#    @year_name.delete_at(0)
    @users = User.all
    @roles = Role.all
    @role = Hash::new
    @roles.each do |role|
      @role["#{role.id}"] = role.position 
    end

    params[:keywords] ||= ""
#    keyword_arrays = params[:keywords].gsub(/　/," ").split()
    keyword_arrays = params[:keywords].split()
#    usermachines = User.arel_table[:machine].pluck(:id)
    usermachines = User.arel_table[:machine]
    usermachines_sel = usermachines.matches("\%#{keyword_arrays[0]}\%")
    for i in 1...keyword_arrays.length
      usermachines_sel = usermachines_sel.or(usermachines.matches("\%#{keyword_arrays[i]}\%"))
    end
    logger.debug("SQL: #{User.where(usermachines_sel).to_sql}")
    @usermachinex = User.where(usermachines_sel).pluck(:id)

    @keyword = params[:keyword]
    @usernamex    = User.where(account: @keyword).pluck(:id)
#    @usermachinex = User.where(machine: @keyword).pluck(:id)
    if @yearserch != 0
       if @keyword == ""
          @users = User.where(year: @year_name[@yearserch]).order(:machine)
          @h1 = "#{@year_name[@yearserch]} 年度のユーザ一覧"
       else
          @users = User.where(year: @year_name[@yearserch], id: @usernamex, id: @usermachinex).order(:machine)
          @h1 = "#{@year_name[@yearserch]} 年度のユーザ検索"
       end
    else
#       if @keyword == ""
          @users = User.where(year: @thisyear.year.to_i).order(:machine)#, :order => 'studentid DESC')
          @h1 = "#{@thisyear.year.to_i} 年度ユーザ一覧"
#       else
#          @users = User.where(year: @thisyear.year.to_i, id: @usernamex, id: @usermachinex)#, :order => 'studentid DESC')
#          @users = User.find(:all)#, :order => 'studentid DESC')
#          @h1 = "#{@thisyear.year.to_i} 年度ユーザ検索"
#       end 
    end
    @user_waiting = User.where(acception: 'f', owner: current_user.account.to_s )
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def indexyear
    params[:keywords] ||= ""
#    keyword_arrays = params[:keywords].gsub(/　/," ").split()
    keyword_arrays = params[:keywords].split()
#    usermachines = User.arel_table[:machine].pluck(:id)
    usermachines = User.arel_table[:machine]
    usermachines_sel = usermachines.matches("\%#{keyword_arrays[0]}\%")
    for i in 1...keyword_arrays.length
      usermachines_sel = usermachines_sel.or(usermachines.matches("\%#{keyword_arrays[i]}\%"))
    end
    logger.debug("SQL: #{User.where(usermachines_sel).to_sql}")
    @usermachinex = User.where(usermachines_sel).pluck(:id)

    @keyword = params[:keyword]
    @usernamex    = User.where(account: @keyword).pluck(:id)
#    @usermachinex = User.where(machine: @keyword).pluck(:id)
    @yearserch = params[:yearserch].to_i
#    @years = Year.all
    @years = Year.order("year DESC")
    @year_name = Array.new
    @years.each do |year|
      @year_name[year.id.to_i] = year.year.to_s
    end
#    @year_name.delete_at(0)
    @users = User.all
    @roles = Role.all
    @role = Hash::new
    @roles.each do |role|
      @role["#{role.id}"] = role.position 
    end
    if @yearserch != 0
       if @keyword == ""
          @users = User.where(year: @year_name[@yearserch]).order(:machine)
          @h1 = "#{@year_name[@yearserch]} 年度のユーザ一覧"
       else
          @users = User.where(year: @year_name[@yearserch], id: @usernamex, id: @usermachinex).order(:machine)
          @h1 = "#{@year_name[@yearserch]} 年度のユーザ検索"
       end
    else
       if @keyword == ""
          @users = User.all.order(:machine)
          @h1 = "全年度ユーザ一覧"
       else
          @users = User.where(id: @usernamex, id: @usermachinex).order(:machine)
          @h1 = "全年度ユーザ検索"
       end 
    end

    @user_waiting = User.where(acception: 'f', owner: current_user.account.to_s)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @role = Role.find(@user.role_id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new
    @role = Role.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  def newext
    @user = User.new
    @role = Role.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
#    @role = Role.find(@user.role_id)
    @role = Role.all
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @role = Role.all
    @thisyear = Year.find_by(default: 't')
    @user.year = @thisyear.year.to_i
    @user.acception = 't'
#    respond_to do |format|
      if @user.save
#        @repbody = @user.create_repbody( :user_id => @user.id )
        redirect_to users_path, :notice => '【メッセージ】ユーザは正しく作成されました.'
      else
        render "new"
      end
    end

  def createext
    @user = User.new(user_params)
    @role = Role.all
    @thisyear = Year.find_by(default: 't')
    @owner = User.find_by(account: @user.owner)
    @user.year = @thisyear.year.to_i
    @user.acception = 'f'
    @user.role_id = 4

#    respond_to do |format|
      if @user.save
        mail = Usermail.newuser(@owner.username, @user.username, @owner.email, @user.email)
        mail.deliver
        render 'accept' and return
        redirect_to users_path, :notice => '【メッセージ】ユーザ登録申請をしました.' and return
      else
        render 'newext'
#        format.html { render action: "new" }
#        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
#      else
#        render 'newext'
#        format.html { render action: "new" }
#        format.json { render json: @user.errors, status: :unprocessable_entity }
#     end
    end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(user_params)
        format.html { redirect_to @user, notice: '【メッセージ】ユーザ情報は正しく更新されました.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  def mypage
    @user = User.find(params[:id])
    @roles = Role.all
    @tag = Tag.all
    @repbody = Repbody.where(user_id: params[:id])
    @tag_name = Array.new
    @tag.each do |tag|
      @tag_name[tag.id.to_i] = tag.tag.to_s
    end
    @tag_name.delete_at(0)
    @role = Hash::new
    @roles.each do |role|
      @role["#{role.id}"] = role.position 
    end

    @thisyear = Year.find_by(default: 't')
    @year_name = Array.new
    @year_name = @thisyear.year.to_i
    @user1 = User.all
    @user2 = User.all
    if @user.machine == "joho03"
      @machine1 =  "joho01"
      @machine2 =  "joho02"
      @user1 = User.where(year: @year_name, machine: @machine1)#@machine1 @machine2)#.order(machine)
      @user2 = User.where(year: @year_name, machine: @machine2)#@machine1 @machine2)#.order(machine)
    elsif @user.machine == "joho06"
      @machine1 =  "joho04"
      @machine2 =  "joho05"
      @user1 = User.where(year: @year_name, machine: @machine1)#@machine1 @machine2)#.order(machine)
      @user2 = User.where(year: @year_name, machine: @machine2)#@machine1 @machine2)#.order(machine)
    elsif @user.machine == "joho09"
      @machine1 =  "joho07"
      @machine2 =  "joho08"
      @user1 = User.where(year: @year_name, machine: @machine1)#@machine1 @machine2)#.order(machine)
      @user2 = User.where(year: @year_name, machine: @machine2)#@machine1 @machine2)#.order(machine)
    elsif @user.machine == "joho12"
      @machine1 =  "joho10"
      @machine2 =  "joho11"
      @user1 = User.where(year: @year_name, machine: @machine1)#@machine1 @machine2)#.order(machine)
      @user2 = User.where(year: @year_name, machine: @machine2)#@machine1 @machine2)#.order(machine)
    elsif @user.machine == "joho15"
      @machine1 =  "joho13"
      @machine2 =  "joho14"
      @user1 = User.where(year: @year_name, machine: @machine1)#@machine1 @machine2)#.order(machine)
      @user2 = User.where(year: @year_name, machine: @machine2)#@machine1 @machine2)#.order(machine)
    elsif @user.machine == "joho18"
      @machine1 =  "joho16"
      @machine2 =  "joho17"
      @user1 = User.where(year: @year_name, machine: @machine1)#@machine1 @machine2)#.order(machine)
      @user2 = User.where(year: @year_name, machine: @machine2)#@machine1 @machine2)#.order(machine)
    elsif @user.machine == "joho27" or @user.machine == "joho21"
      @machine1 =  "joho19"
      @machine2 =  "joho20"
      @user1 = User.where(year: @year_name, machine: @machine1)#@machine1 @machine2)#.order(machine)
      @user2 = User.where(year: @year_name, machine: @machine2)#@machine1 @machine2)#.order(machine)
    else @user.machine == "joho24"
      @machine1 =  "joho22"
      @machine2 =  "joho23"

app/helpers/users_helper.rb
module UsersHelper
  # 与えられたユーザーのGravatar (http://gravatar.com/) を返す。
  def gravatar_for(current_user)
    gravatar_id = Digest::MD5::hexdigest(current_user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: current_user.account, class: "gravatar")
  end
end

app/views/users/accept.html.erb
<p id="notice"><%= notice %></p>
<h1>ユーザ登録申請を送信しました</h1>
<p> 少々お待ちください </p>
<p><%= link_to 'ログインページ', login_path %></p>

app/views/users/chpass.html.erb
<h1>ユーザ情報の編集</h1>
<div id="mainbody">
  <div id="container">
    <div id="mainbox">
      <div id="imagebox">
        <!-- userimage  -->
        <div class="field">
          <%= image_tag current_user.avatar.url, :size => "200x200" %>
        </div>
        <%= link_to 'Edit', avatar_path(@user) %> 
      </div> <!-- imagebox -->
      <div id="mainfield">
	<!-- メインコンテンツ  -->
	<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
	<div id="error_explanation">
	  <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
	  
	  <ul>
	    <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
	    <% end %>
	  </ul>
	</div>
	<% end %>


        <div class="field">
          <b>Year:</b>
          <%= @user.year %>
        </div>

        <div class="field">
          <b>ID:</b>
          <%= @user.id %>
        </div>

        <div class="field">
          <b>Account:</b>
          <%= @user.account %>
        </div>

        <div class="field">
          <b>Username:</b>
          <%= @user.username %>
        </div>

        <div class="field">
          <b>Furigana:</b>
          <%= @user.furigana %>
        </div>

        <div class="field">
          <b>Studentid:</b>
          <%= @user.studentid %>
        </div>

        <div class="field">
          <b>Role:</b>
          <%= @user.role.position %>
        </div>

        <div class="field">
          <b>Grade:</b>
          <%= @user.grade %>
        </div>

        <% unless @role["#{current_user.role_id}"] == '受講生' %>
	  <%= f.label :情報実験機　「担当テーブルの3N機」 %>  
	  <%= f.text_field :machine %>  
        <% else %>
        <div class="field">
          <b>Machine:</b>
          <%= @user.machine %>
        </div>
        <% end %>

	<div class="field">  
	  <%= f.label :メールアドレス %>  
	  <%= f.text_field :email %>  
	</div>  
	
	<div class="field">  
	  <%= f.label :パスワード %>  
	  <%= f.password_field :password %> 
	</div>  
	<div class="field">  
	  <%= f.label :パスワード確認 %>  
	  <%= f.password_field :password_confirmation %>  
	</div>  
	<div class="actions">
	  <%= f.submit %>
	</div>
	<% end %>
      </div>
    </div>
    <div id="sidebox">
      <div id="sidemenu">
	<!-- サイドメニュー  -->
	<%= render 'shared/sidemenu_public' %>
      </div>
    </div>
  </div>
</div>

app/views/users/mypage.html.erb
<p id="notice"><%= notice %></p>

<h1>マイページ
</h1>
<div id="mainbody">
  <div id="container">
    <div id="mainbox">
      <div id="maypagefield">
	<h2><%= current_user.account %> さんのレポート提出状況は以下のようになっています.</h2>
        <p> Tag とCreateDate が赤いのは，遅刻レポートを示しており，Title が赤いのは，要修正箇所があるレポートを示しています．</p>

	<%# if @role["#{current_user.role_id}"] == 'TA' or @role["#{current_user.role_id}"] == 'VTA' %>
	<% unless @role["#{current_user.role_id}"] == '受講生' %>
	<div style="height:100px; width:720px; overflow-y:scroll; overflow-y:auto;">
	<% end %>
	<table border="1" width="700px">
	  <tr>
	    <th></th>
	    <th>User</th>
	    <th>Tag</th>
	    <th>CreateDate</th>
	    <th>LastUpDate</th>
	    <th>Title</th>
	    <th>コメント有無</th>
	    <th colspan="3">アクション</th>
	  </tr>
	  <% nm = 1%>
	  <% @repbody.each do |repbody| %>
	  <tr style="background-color:<%= cycle('#ffffff', '#d3d3d3') %>">
	    <td><%= nm %></td>
	    <td><%= repbody.user.username %></td>
	    <td>
              <% if repbody.created_at.strftime("%Y%m%d%H%M") <= Time.parse(repbody.tag.deadline).strftime("%Y%m%d%H%M") %>
	        <%= repbody.tag.tag %><%#= @tag_name[repbody.tag_id.to_i - 1].to_s %>
              <% else %>
	        <font color="red"><%= repbody.tag.tag %><%#= @tag_name[repbody.tag_id.to_i - 1].to_s %></font>
	      <% end %>

	    </td>
	    <td>
              <% if repbody.created_at.strftime("%Y%m%d%H%M") <= Time.parse(repbody.tag.deadline).strftime("%Y%m%d%H%M") %>
	        <%= truncate(repbody.created_at.to_s, :length => 19, :omission => '') %>
              <% else %>
	        <font color="red"><%= truncate(repbody.created_at.to_s, :length => 19, :omission => '') %> </font>
	      <% end %>
	    </td>

	    <td><%= truncate(repbody.updated_at.to_s, :length => 19, :omission => '') %></td>
            <td>
              <% if repbody.fix == false  %>
                <b><font color="red"><%= repbody.title %> </font></b>
              <% else %>
                <%= repbody.title %>
              <% end %>
            </td>
	    <td><%= repbody.commentexis %></td>
	    <td><%= link_to 'Show', user_repbody_path(repbody.user_id, repbody.id) %></td>
	    
	    <td>
	      <% if current_user.id.to_i == repbody.user_id.to_i %>
	      <%= link_to 'Edit', edit_user_repbody_path(current_user, repbody.id) %>
	      <% end %>
	    </td>
	    
	  </tr>
	  <% nm = nm + 1 %>
	  <% end %>
	</table>
	<% unless @role["#{current_user.role_id}"] == '受講生' %>
	<%# if @role["#{current_user.role_id}"] == 'TA' or @role["#{current_user.role_id}"] == 'VTA' %>
	</div>
	<% end %>

	<%# unless @role["#{current_user.role_id}"] == '受講生' %>
	<% if @role["#{current_user.role_id}"] == 'TA' or @role["#{current_user.role_id}"] == 'VTA' %>
	<h2>担当テーブルの受講生の最近のレポート提出状況</h2>
	<p> 現在の担当情報実験機は <%= @machine1 %>, <%= @machine2 %> です．<br>
	担当テーブルの変更は <%= link_to 'こちら', chpass_path(current_user.id) %> から</p>
	<br>
	<div style="width:720px;">
        <div style="height:300px; width:350px; overflow-y:scroll; overflow-y:auto; float:left;">
        <h3> <%= @machine1 %> </h3>
        <% @user1.each do |user| %>
          <% if user.acception %>
            <% if user.machine == @machine1  %>
	     <p><b><%= user.username %></b>，<%= link_to 'レポートをすべて見る', userreportshow_path(user.id) %></p>
             <table border="1" width="330px">
               <tr>
                 <th>Tag</th>
                 <th>LastUpDate</th>
                 <th>Title and Show</th>
               </tr>
               <% nm = 1%>
               <% @repbodies1 = Repbody.where(user_id: user.id).order(:updated_at).reverse_order.limit(3) %>
  	       <% @repbodies1.each do |repbody| %>
               <% if user.account == repbody.user.account%>
               <tr style="background-color:<%= cycle('#ffffff', '#d3d3d3') %>">
	         <td><%= repbody.tag.tag %> </td>
                 <td><%= truncate(repbody.updated_at.to_s, :length => 19, :omission => '') %></td>
                 <td><%= link_to repbody.title, user_repbody_path(repbody.user_id, repbody.id) %></td>
	       </tr>
               <% end %>
	    <% end %>
            </table>
	    <br>
	    <% end %>
   	  <% end %>
	<% end %>
        </div>

        <div style="height:300px; width:350px; overflow-y:scroll; overflow-y:auto; float:left;">
        <h3> <%= @machine2 %> </h3>

        <% @user2.each do |user| %>
          <% if user.acception %>
            <% if user.machine == @machine2  %>
	     <p><b><%= user.username %></b>，<%= link_to 'レポートをすべて見る', userreportshow_path(user.id) %></p>
             <table border="1" width="330px">
               <tr>
                 <th>Tag</th>
                 <th>LastUpDate</th>
                 <th>Title and Show</th>
               </tr>
               <% nm = 1%>
               <% @repbodies2 = Repbody.where(user_id: user.id).order(:updated_at).reverse_order.limit(3) %>
  	       <% @repbodies2.each do |repbody| %>
               <% if user.account == repbody.user.account%>
               <tr style="background-color:<%= cycle('#ffffff', '#d3d3d3') %>">
	         <td><%= repbody.tag.tag %> </td>
                 <td><%= truncate(repbody.updated_at.to_s, :length => 19, :omission => '') %></td>
                 <td><%= link_to repbody.title, user_repbody_path(repbody.user_id, repbody.id) %></td>
	       </tr>
               <% end %>
               <% end %>
             </table>
	    <br>
	    <% end %>
   	  <% end %>
	<% end %>
        </div>
	<br>
	</div>
	<% end %>
        <hr>
        <br>
      </div>
    </div>

    <div id="sidebox">
      <div id="sidemenu">
	<%= render "shared/sidemenu_adm" %>
	<%= render "shared/sidemenu_public" %>
      </div>
    </div>

  </div>
</div>

app/views/users/userreportshow.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.account %>さんのレポート一覧</h1>

<div id="mainbody">
  <div id="container">
    <div id="mainbox">
      <div id="mainfield">
	<!-- メインコンテンツ  -->
	<%= @user.account %> さんのレポート提出状況は以下のようになっています.
	
	<table border="1">
	  <tr>
	    <th></th>
	    <th>ID</th>
	    <th>User</th>
	    <th>ふりがな</th>
	    <th>Tag</th>
	    <th>Date</th>
	    <th>Title</th>
	    <th>Body</th>
	    <th>コメント有無</th>
	    <th colspan="2">アクション</th>
	  </tr>
	  <% nm = 1%>
	  <% @repbody.each do |repbody| %>
	  <tr style="background-color:<%= cycle('#ffffff', '#d3d3d3') %>">
	    
	    <td><%= nm %></td>
	    <td><%= repbody.id %></td>
	    <td><%= repbody.user.username %></td>
	    <td><%= repbody.user.furigana %></td>
	    <td><%= repbody.tag.tag %><%#= @tag_name[repbody.tag_id.to_i - 1].to_s %></td>
	    <td><%= repbody.date %></td>
	    <td><%= repbody.title %></td>
	    <td><%= truncate(repbody.body, :length => 10) %></td>
	    <td><%= repbody.commentexis %></td>
	    <td><%= link_to 'Show', user_repbody_path(repbody.user_id, repbody.id) %></td>
	    
	    <td>
	      <% if current_user.id.to_i == repbody.user_id.to_i %>
	      <%= link_to 'Edit', edit_user_repbody_path(current_user, repbody.id) %>
	      <% end %>
	    </td>
	    
	  </tr>
	  <% nm = nm + 1 %>
	  <% end %>
	</table>
	
      </div>
    </div>
    <div id="sidebox">
      <div id="sidemenu">
	<!-- サイドメニュー  -->
	<%= render 'shared/sidemenu_public' %>
      </div>
    </div>
  </div>
</div>