config/routes.rb
Rails.application.routes.draw do

  resources :tags

  resources :repbodies, :only=> %w[show index opinion destroy]

  resources :roles

  resources :users do
    resources :fileupload, :only => %w[index]
    resources :repbodies do #, :except => %w[new create destroy]
      resources :comments do
        resources :usercomments
      end
    end
  end
  resources :users#, :only => %w[indexyear] #, :except => %w[new create destroy update edit]

  resources :sessions 
  get "login" => "sessions#new", :as => "login" 
  get "logout" => "sessions#destroy", :as => "logout" 
  get "userapplicate" => "users#newext", :as => "userapplicate" 
  post "createext" => "users#createext", :as => "createext" , :via => "get"
  post "indexyear" => "users#indexyear", :as => "indexyear" , :via => "get"
  post "upload_process" => "fileupload#upload_process", :as => "upload_process" , :via => "get"
  post "repbodies" => "repbodies#index",  :via => "get"
  post "indexyeartag" => "repbodies#indexyeartag", :as => "indexyeartag", :via => "get"
  match '/acception/:id' => 'users#acception', :as => "acception", :via => "get"
  match '/mypage/:id' => 'users#mypage', :as => "mypage", :via => "get"
  match '/chpass/:id' => 'users#chpass', :as => "chpass", :via => "get"
  match '/userreportshow/:id' => 'users#userreportshow', :as => "userreportshow", :via => "get"
  match '/opinion/' => 'repbodies#opinion', :as => "opinion", :via => "get"
  match '/fileupload/' =>  'fileupload#upload', :via => "get"
  match '/years/' =>  'years#index', :via => [:get, :post]
  match '/avatar/:id' =>  'users#avatar',  :as => "avatar", :via => "get"
  match 'indexyear' => 'users#indexyear',  :via => "get"
  match 'indexyeartag' => 'repbodies#indexyeartag', :via => "get"

  match ':controller(/:action(/:id))(.:format)', :via => "get"
  root :to => 'showindex#index'
end

app/models/repbody.rb
class Repbody < ActiveRecord::Base
#  attr_accessible :body, :date, :tag_id, :title, :user_id
  belongs_to :user
  belongs_to :tag
  has_many :comments
  has_many :usercomments
  has_many :updates
  has_many :hyperlinks
  accepts_nested_attributes_for :hyperlinks
private
def role_params
    params.require(:repbody).permit(:body, :date, :tag_id, :title, :user_id, :fix)
end
end

app/controllers/repbodies_controller.rb
# -*- coding: utf-8 -*-
class RepbodiesController < ApplicationController
  before_filter :user_checked, :except => ['index', 'show', 'indexyeartag']
  before_filter :edit_checked, :only => ['edit']
  before_filter :year_checked, :except => ['index','show', 'indexyeartag']

  # GET /repbodies
  # GET /repbodies.json
  def index
    @thisyear = Year.find_by(default: 't')
    @yearserch = params[:yearserch].to_i
    @years = Year.all
#    @years = Year.order("year DESC")
    @years = Year.order("updated_at DESC")
    @year_name = Array.new
    @years.each do |year|
      @year_name[year.id.to_i] = year.year.to_s
    end

    @tagserch = 0
    @tagserch = params[:tagserch].to_i
#    @tags = Tag.all
#    @tags = Tag.order("tag DESC")
    @tags = Tag.order("updated_at DESC")
    @tag_name = Array.new
    @tags.each do |tag|
      @tag_name[tag.id.to_i] = tag.tag.to_s
    end
    @tag_name.delete_at(0)

    params[:keywords] ||= ""
#    keyword_arrays = params[:keywords].gsub(/　/," ").split()
    keyword_arrays = params[:keywords].split()
    usermachines = User.arel_table[:machine]
    usermachines_sel = usermachines.matches("\%#{keyword_arrays[0]}\%")
    for i in 1...keyword_arrays.length
      usermachines_sel = usermachines_sel.or(usermachines.matches("\%#{keyword_arrays[i]}\%"))
    end
    logger.debug("SQL: #{User.where(usermachines_sel).to_sql}")
    @usermachinex = User.where(usermachines_sel).pluck(:id)
    @usernamex    = User.where(usermachines_sel).pluck(:id)

    @users = User.all
#    @keyword = params[:keyword]
#    @usernamex    = User.where(account: @keyword).pluck(:id)
#    @usermachinex = User.where(machine: @keyword).pluck(:id)
#    if @usermachinex == "[]" && @usernamex == "[]"
#       @userserch = 0
#    elsif @usermachinex != "[]" && @usernamex === "[]"
#       @userserch = User.where(machine: @keyword).pluck(:id)
#    elsif @usermachinex === "[]" && @usernamex != "[]"
#       @userserch = User.where(account: @keyword).pluck(:id)
#    else
#       @userserch = 99
#    end
    @usernameh = Hash::new
    @usermachineh = Hash::new
    @users.each do |user|
      @usernameh["#{user.id}"] = user.account
      @usermachineh["#{user.id}"] = user.machine 
    end

    if @tagserch != 0 && @yearserch != 0 
      if @keyword == ""
      @repbodies = Repbody.where(year: @year_name[@yearserch], tag_id: @tagserch).order(:updated_at).reverse_order
      @h1 = "#{@year_name[@yearserch]} 年度のタグ「#{@tag_name[@tagserch -1]}」のレポート一覧"
      else 
#      @repbodies = Repbody.where(year: @year_name[@yearserch], tag_id: @tagserch, user_id: @userserch)
      @repbodies = Repbody.where(year: @year_name[@yearserch], tag_id: @tagserch, user_id: [@usernamex, @usermachinex]).order(:updated_at).reverse_order
      @h1 = "#{@year_name[@yearserch]} 年度のタグ「#{@tag_name[@tagserch -1]}」のレポート検索結果"
      end
    elsif @tagserch == 0 && @yearserch != 0
      if @keyword == ""
      @repbodies = Repbody.where(year: @year_name[@yearserch]).order(:updated_at).reverse_order
      @h1 = "#{@year_name[@yearserch]} 年度のレポート一覧"      
      else
      @repbodies = Repbody.where(year: @year_name[@yearserch], user_id: [@usernamex, @usermachinex]).order(:updated_at).reverse_order

#      @repbodies = Repbody.where(year: @year_name[@yearserch], user_id: @userserch)#, order: 'updated_at DESC')
      @h1 = "#{@year_name[@yearserch]} 年度のレポート検索結果"      
      end
    elsif @tagserch != 0 && @yearserch == 0
      if @keyword == ""
      @repbodies = Repbody.where(tag_id: @tagserch).order(:updated_at).reverse_order
      @h1 = "全年度のタグ「#{@tag_name[@tagserch - 1]}」のレポート一覧"      
      else
      @repbodies = Repbody.where(tag_id: @tagserch, user_id: [@usernamex, @usermachinex]).order(:updated_at).reverse_order
#      @repbodies = Repbody.where(tag_id: @tagserch, user_id: @userserch)#, order: 'updated_at DESC')
      @h1 = "全年度のタグ「#{@tag_name[@tagserch - 1]}」のレポート検索結果"      
      end
    else
      if @keyword != ""
      @repbodies = Repbody.where(user_id: [@usernamex, @usermachinex]).order(:updated_at).reverse_order
      @h1 = "全レポートの検索結果"
      else
      @repbodies = Repbody.order(:updated_at).reverse_order
      @h1 = "全レポート一覧"
      end
    end

    @comment = Comment.all
#    @role = Role.find(:first, :conditions => ["position = ?", '受講生'])
    @roleh =Hash::new
    @roles = Role.all
    @roles.each do |role|
      @roleh["#{role.id}"] = role.position
    end
    respond_to do |format|
      format.html # index.html.erb   
      format.json { render json: @repbodies }
    end
  end

  def indexyeartag
    @thisyear = Year.find_by(default: 't')
    @yearserch = params[:yearserch].to_i
    @years = Year.all
    @years = Year.order("updated_at DESC")
    @year_name = Array.new
    @years.each do |year|
      @year_name[year.id.to_i] = year.year.to_s
    end

    @tagserch = 0
    @tagserch = params[:tagserch].to_i
#    @tags = Tag.all
#    @tags = Tag.order("tag DESC")
    @tags = Tag.order("updated_at DESC")
    @tag_name = Array.new
    @tags.each do |tag|
      @tag_name[tag.id.to_i] = tag.tag.to_s
    end
    @tag_name.delete_at(0)

    params[:keywords] ||= ""
#    keyword_arrays = params[:keywords].gsub(/　/," ").split()
    keyword_arrays = params[:keywords].split()
    usermachines = User.arel_table[:machine]
    usermachines_sel = usermachines.matches("\%#{keyword_arrays[0]}\%")
    for i in 1...keyword_arrays.length
      usermachines_sel = usermachines_sel.or(usermachines.matches("\%#{keyword_arrays[i]}\%"))
    end
    logger.debug("SQL: #{User.where(usermachines_sel).to_sql}")
    @usermachinex = User.where(usermachines_sel).pluck(:id)
    @usernamex    = User.where(usermachines_sel).pluck(:id)

    @users = User.all
    @usernameh = Hash::new
    @usermachineh = Hash::new
    @users.each do |user|
      @usernameh["#{user.id}"] = user.account
      @usermachineh["#{user.id}"] = user.machine 
    end

    if @tagserch != 0 && @yearserch != 0 
      if @keyword == ""
      @repbodies = Repbody.where(year: @year_name[@yearserch], tag_id: @tagserch)
      @h1 = "#{@year_name[@yearserch]} 年度のタグ「#{@tag_name[@tagserch -1]}」のレポート一覧"
      else 
      @repbodies = Repbody.where(year: @year_name[@yearserch], tag_id: @tagserch, user_id: [@usernamex, @usermachinex])
      @h1 = "#{@year_name[@yearserch]} 年度のタグ「#{@tag_name[@tagserch -1]}」のレポート検索結果"
      end
    elsif @tagserch == 0 && @yearserch != 0
      if @keyword == ""
      @repbodies = Repbody.where(year: @year_name[@yearserch])#, order: 'updated_at DESC')
      @h1 = "#{@year_name[@yearserch]} 年度のレポート一覧"      
      else
      @repbodies = Repbody.where(year: @year_name[@yearserch], user_id: [@usernamex, @usermachinex])
      @h1 = "#{@year_name[@yearserch]} 年度のレポート検索結果"      
      end
    elsif @tagserch != 0 && @yearserch == 0
      if @keyword == ""
      @repbodies = Repbody.where(tag_id: @tagserch)#, order: 'updated_at DESC')
      @h1 = "全年度のタグ「#{@tag_name[@tagserch - 1]}」のレポート一覧"      
      else
      @repbodies = Repbody.where(tag_id: @tagserch, user_id: [@usernamex, @usermachinex])
      @h1 = "全年度のタグ「#{@tag_name[@tagserch - 1]}」のレポート検索結果"      
      end
    else
#      if @keyword != ""
#      @repbodies = Repbody.where(user_id: @usernamex, user_id: @usermachinex)#.order(update_at: :DESC)
#      @h1 = "全レポートの検索結果"
#      else
      @repbodies = Repbody.order(updated_at: :DESC)
      @h1 = "レポート一覧"
#      end
    end

    @comment = Comment.all
    @roleh =Hash::new
    @roles = Role.all
    @roles.each do |role|
      @roleh["#{role.id}"] = role.position
    end
    respond_to do |format|
      format.html # index.html.erb   
      format.json { render json: @repbodies }
    end
  end

  # GET /repbodies/opinion
  # GET /repbodies/opinion.json
  def opinion
    @users = User.all
    @usernameh = Hash::new
    @users.each do |user|
      @usernameh["#{user.id}"] = user.username 
    end
    @tags = Tag.all
    @tag_name = Array.new
    @tags.each do |tag|
      @tag_name[tag.id.to_i] = tag.tag.to_s
    end
    @tag_name.delete_at(0)
    @repbodies = Repbody.find_all_by_tag_id(6, :order => 'updated_at DESC')
    @comment = Comment.all
    @role = Role.find(:first, :conditions => ["position = ?", '受講生'])
    respond_to do |format|
      format.html # opinion.html.erb   
      format.json { render json: @repbodies }
    end
  end

  # GET /repbodies/1
  # GET /repbodies/1.json
  def show
    @repbodyidshow = Repbody.find(params[:id])
#    @commentidshow = Comment.find(params[:id])
    @commentidshow = Comment.find_by(repbody_id: @repbodyidshow.id)
    @users = User.all
    @usernameh = Hash::new
    @users.each do |user|
      @usernameh["#{user.id}"] = user.username 
    end
    @tag = Tag.find(@repbodyidshow.tag_id)
    @comments = Comment.where(repbody_id: @repbodyidshow.id)
#    @usercomments = Usercomment.find_by(repbody_id: @repbodyidshow.id, comment_id: @commentidshow.id)
    @usercomments = Usercomment.where(repbody_id: @repbodyidshow.id)
    @updates = Update.where(repbody_id: @repbodyidshow.id)
    @hyperlinks = Hyperlink.where(repbody_id: @repbodyidshow.id)
    @urlhere = request.url
    @roleh =Hash::new
    @roles = Role.all
    @roles.each do |role|
      @roleh["#{role.id}"] = role.position
    end
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @repbody }
    end
  end

  # GET /repbodies/new
  # GET /repbodies/new.json
  def new
    @repbody = Repbody.new
      @slink = Array.new
    for i in 1..5 do
      @hyperlink_#{i} = Hyperlink.new
      @slink << @hyperlink_#{i}
    end

#    @tag = Tag.all
    @thisyear = Year.find_by(default: 't')
    @yearname = @thisyear.year.to_s
#    @tag = Tag.find(:all, :conditions => [ "tag like ? ", '%2014%' ] )
    @tag = Tag.where("tag like ? ", "%[#{@yearname}]%" )

    if current_user.id
      @repbody.user_id = current_user.id
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @repbody }
    end
  end

  # GET /repbodies/1/edit

app/helpers/repbodies_helper.rb
module RepbodiesHelper
end

app/views/repbodies/edit.html.erb
<h1>レポートの更新</h1>

<%= render 'form' %>

app/views/repbodies/index.html.erb
<h1><%= @h1 %></h1>

<div id="mainbody">
  <div id="container">
    <div id="mainbox">
	<p>
	  ここではすべてのレポートを一覧することができます. 受講生であれば show, さらに自分の書いたレポートであれば edit することができます. TA, VTA, Staff であればコメントを付与することができます.
	</p>

      <div id="mainfield">

	<!-- メインコンテンツ  -->
	<p>
	  検索，検索ゥゥ!!
	  <%= form_tag(:action => "index") do %>
	  <%= select_tag('tagserch', options_from_collection_for_select(@tags, :id, :tag, @tagserch ), :prompt => "すべてを表示") %>
	  <%= select_tag('yearserch', options_from_collection_for_select(@years, :id, :year, @thisyear.id.to_i ), :prompt => "すべてを表示") %> 年度の
          <%= text_field_tag :keywords, params[:keywords], :placeholder => ' johoXX', :size => '5px' %>
	  <%= submit_tag '絞り込み', :name => nil%>
	  <% end %>
	</p>
	<br>
        <% if current_user.id == "1" %>

	<table border="1" width="700px">
	  <tr>
	    <th>Year</th>
	    <th>User</th>
	    <th>情報実験機番号</th>
	    <th>Tag</th>
	    <th>create date</th>
	    <th>last update</th>
	    <th>Title</th>
	    <th >コメント有無</th>
	    <th colspan="3">アクション</th>
	    <th>レポート抹消</th>
	  </tr>
	  
	  
	  <% @repbodies.each do |repbody| %>
	  
	  <tr style="background-color:<%= cycle('#ffffff', '#d3d3d3') %>">
	    <td><%= repbody.year %></td>
	    <td><%= p @usernameh["#{repbody.user_id}"] %></td>
	    <td><%= p @usermachineh["#{repbody.user_id}"] %></td>
	    <td>
                <% if repbody.created_at.strftime("%Y%m%d%H%M") <= Time.parse(repbody.tag.deadline).strftime("%Y%m%d%H%M") %>
		<%= @tag_name[repbody.tag_id.to_i - 1].to_s %>
              <% else %>
                <font color="red"><%= @tag_name[repbody.tag_id.to_i - 1].to_s %></font>
              <% end %>
	    </td>
            <td>
                <% if repbody.created_at.strftime("%Y%m%d%H%M") <= Time.parse(repbody.tag.deadline).strftime("%Y%m%d%H%M") %>
                <%= truncate(repbody.created_at.to_s, :length => 19, :omission => '') %>
              <% else %>
                <font color="red"><%= truncate(repbody.created_at.to_s, :length => 19, :omission => '') %> </font>
              <% end %>
            </td>
            <td><%= truncate(repbody.updated_at.to_s, :length => 19, :omission => '') %></td>
            <td>
              <% if repbody.fix == false  %>
                <b><font color="red"><%= repbody.title %> </font></b>
              <% else %>
                <%= repbody.title %>
              <% end %>
            </td>
	    <td><%= repbody.commentexis.to_s %></td>
	    <td><%= link_to 'Show', user_repbody_path(repbody.user_id, repbody.id) %></td>
	    <td>
	      <% if current_user.id.to_i == repbody.user_id.to_i %>
	      <%= link_to 'Edit', edit_user_repbody_path(current_user, repbody.id) %>
	      <% end %>
	    </td>
	    <td>
	      <% unless @roleh[current_user.role_id.to_i] == '受講生' %>
	      <%= link_to 'コメント', new_user_repbody_comment_path(current_user, repbody.id) %></td>
	    <% end %>
            <td><%= link_to 'Destroy', repbody, confirm: 'Are you sure?', method: :delete %></td>
    	  </tr>
	  <% end %>
	</table>

        <% else %>

	<table border="1" width="700px">
	  <tr>
	    <th>Year</th>
	    <th>User</th>
	    <th>情報実験機番号</th>
	    <th>Tag</th>
	    <th>create date</th>
	    <th>last update</th>
	    <th>Title</th>
	    <th >コメント有無</th>
	    <th colspan="3">アクション</th>
	  </tr>
	  
	  
	  <% @repbodies.each do |repbody| %>
	  
	  <tr style="background-color:<%= cycle('#ffffff', '#d3d3d3') %>">
	    <td><%= repbody.year %></td>
	    <td><%= p @usernameh["#{repbody.user_id}"] %></td>
	    <td><%= p @usermachineh["#{repbody.user_id}"] %></td>
	    <td><%= @tag_name[repbody.tag_id.to_i - 1].to_s %></td>
	    <td><%= truncate(repbody.created_at.to_s, :length => 19, :omission => '') %></td>
	    <td><%= truncate(repbody.updated_at.to_s, :length => 19, :omission => '') %></td>
	    <td><%= repbody.title %></td>
	    <td><%= repbody.commentexis.to_s %></td>
	    <td><%= link_to 'Show', user_repbody_path(repbody.user_id, repbody.id) %></td>
	    <td>
	      <% if current_user.id.to_i == repbody.user_id.to_i %>
	      <%= link_to 'Edit', edit_user_repbody_path(current_user, repbody.id) %>
	      <% end %>
	    </td>
	    <td>
	      <% unless @roleh[current_user.role_id.to_i] == '受講生' %>
	      <%= link_to 'コメント', new_user_repbody_comment_path(current_user, repbody.id) %></td>
	    <% end %>
	    
	  </tr>
	  <% end %>
	</table>
	  <% end %>
	
	<br />
	
	<%= link_to 'マイページ', mypage_path(current_user.id) %>
	
	
      </div>
    </div>
    <div id="sidebox">
      <div id="sidemenu">
	<!-- サイドメニュー  -->
	<%= render 'shared/sidemenu_public' %>
      </div>
    </div>
  </div>
</div>

app/views/repbodies/new.html.erb
<h1>新規レポート投稿</h1>


<%= render 'newform' %>

app/views/repbodies/opinion.html.erb
<h1>目安板</h1>

<p>
  ご意見頂戴誠にありがとうございます. このページはタグ「目安板」を集めたページです. 新 RPS に関するご意見はテストも兼ねてこちらへどうぞ. こちらへと書きましたが, [マイページ]=>[新規投稿] でタグを [目安板] にしてください.
</p>

<table border="1" width="800px">
  <tr>
    <th>User</th>
    <th>Tag</th>
    <th>Date</th>
    <th>Title</th>
    <th >コメント有無</th>
    <th colspan="3">アクション</th>
  </tr>


<% @repbodies.each do |repbody| %>

  <tr style="background-color:<%= cycle('#ffffff', '#d3d3d3') %>">
    <td><%= p @usernameh["#{repbody.user_id}"] %></td>
    <td><%= @tag_name[repbody.tag_id.to_i - 1].to_s %></td>
    <td><%= truncate(repbody.updated_at.to_s, :length => 19, :omission => '') %></td>
    <td><%= repbody.title %></td>
    <td><%= repbody.commentexis.to_s %></td>
    <td><%= link_to 'Show', user_repbody_path(repbody.user_id, repbody.id) %></td>
    <td>
      <% if current_user.id.to_i == repbody.user_id.to_i %>
      <%= link_to 'Edit', edit_user_repbody_path(current_user, repbody.id) %>
      <% end %>
    </td>
    <td>
      <% unless current_user.role_id.to_i == @role.id.to_i %>
      <%= link_to 'コメント', new_user_repbody_comment_path(current_user, repbody.id) %></td>
      <% end %>

  </tr>
<% end %>
</table>

<br />

<%= link_to 'マイページ', mypage_path(current_user.id) %>

app/views/repbodies/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @repbodyidshow.title %></h1>
<!-- さんのレポート提出状況は以下のようになっています.-->
<div id="mainbody">
  <div id="container">
    <div id="mainbox">
      <div id="imagebox">
        <!-- userimage  -->
        <p>
           <%= image_tag current_user.avatar.url, :size => "200x200" %>
          <!-- <%= image_tag("@user.image", :size => "150x150") %> -->
        </p>
      </div> <!-- imagebox -->
コメントに返信する
      <div id="mainfield">
	<!-- メインコンテンツ  -->
	<p>
	  <b>ユーザ名:</b>
	  <%= @repbodyidshow.user.username %>
	</p>

	<p>
	  <b>ふりがな:</b>
	  <%= @repbodyidshow.user.furigana %>
	</p>

	<p>
	  <b>アカウント名:</b>
	  <%= @repbodyidshow.user.account %>
	</p>

	<p>
	  <b>情報実験機番号:</b>
	  <%= @repbodyidshow.user.machine %>
	</p>
	
	<p>
	  <b>Tag:</b>
	  <%= @tag.tag %>
	</p>
	
	<p>
	  <b>更新履歴:</b><br>
	  <% @updates.each do |update|%>
	  <%= update.date %>: <%= update.comment %><br>
	  <% end %>
	</p>
	<table width="700px" border="0" cellspacing="1" bgcolor="#c71585">
	  <tr bgcolor="#c71585" align="left">
	    <th>
	      <p>
		<font color="#ffffff">
		  <b>Title:</b>
		  <%= @repbodyidshow.title %>
		</font>
	      </p>
	      
	    </th>
	  </tr>
	  <tr>
	    <td bgcolor="#ffffff">
	      <pre><%=h @repbodyidshow.body -%></pre>
	      <%#=h preautolink(@repbodyidshow.body) -%>
	    </td>
	  </tr>
	</table>


	<table width="700px" border="0" cellspacing="1" bgcolor="#c71585">
	  <tr bgcolor="#c71585" align="left">
	      <th><b><font color="#ffffff"> リンク名 </font></b></th>
	      <th><b><font color="#ffffff"> URL </font></b></th>
	  </tr>

	  <% @hyperlinks.each do |hlink| %>
	  <tr style="background-color:<%= cycle('#ffffff', '#d3d3d3') %>">
	    <td><%= hlink.title %>
	    <td><%= link_to(hlink.link, hlink.link) %></td>
	  </tr>
	  <% end %>

	</table>

	<% unless @roleh[current_user.role_id.to_i] == '受講生' %>
	<td><%= link_to 'コメントする', new_user_repbody_comment_path(current_user, @repbodyidshow.id) %></td>
        <% end %>
	
	<h2>コメント</h2>
	
	<% @comments.each do |comment| %>
	<table width="700px" border="1" cellspacing="1" bgcolor="#c71585" bordercolor="#c71585">
	  <tr bgcolor="#c71585" align="left">
	    <th>
	      <font color="#ffffff">
		<%= image_tag comment.user.avatar.url, :size => "30x30" %> | <%= p @usernameh["#{comment.user_id}"] %> | <%= comment.updated_at %>
	      </font>
              <% if current_user.id.to_i == comment.user_id.to_i %>
             | 
              <%= link_to '編集する', edit_user_repbody_comment_path(current_user, @repbodyidshow.id, comment.id) %>
              <% end %>
	    </th>
	  </tr>
	  <tr>
	    <td bgcolor="#ffffff">
	      <pre><%= comment.body %></pre>
	    </td>
	  </tr>
	</table>

        <% if current_user.id.to_i == @repbodyidshow.user_id.to_i %>
          <td><%= link_to 'コメントに返信する', new_user_repbody_comment_usercomment_path(current_user, @repbodyidshow.id, comment.id) %></td>
        <% end %>

        <% @usercomments.each do |usercomment| %>
        <% if comment.id == usercomment.comment_id %>
        <table width="500px" border="2" cellspacing="1" bgcolor="#c71585" style="margin-left:200px;">
          <tr bgcolor="#c71585" align="left">
            <th>
              <font color="#ffffff">
               <%= image_tag usercomment.user.avatar.url, :size => "30x30" %> | <%= p @usernameh["#{usercomment.user_id}"] %> | <%= usercomment.updated_at %>
              </font>
<!--         <% if current_user.id.to_i == usercomment.user_id.to_i %> -->
<!--             | -->
<!--             <%= link_to '編集する', edit_user_repbody_comment_usercomment_path(current_user, @repbodyidshow.id, @commentidshow.id, usercomment.id) %> -->
<!--              <% end %> -->
            </th>
          </tr>
          <tr>
            <td bgcolor="#ffffff">
              <pre><%= usercomment.body %></pre>
            </td>
          </tr>
        </table>
        <div style="margin-left:150px; width:550px">
        <hr>
        </div>
        <% end %>
	<% end %>
        <p>--------------------------</p>

	<% end %>

	<% unless @comments[0] %>
        <p> コメントはまだ何もありません.</p>
	<% end %>
	
	
        <p>
	  このページの URL <br>
	  <%= @urlhere %>
	</p>
</div>
</div>
<div id="sidebox">
  <div id="sidemenu">
    <!-- サイドメニュー  -->
    <%= render 'shared/sidemenu_public' %>
  </div>
</div>
</div>
</div>