config/routes.rb
Rails.application.routes.draw do

  resources :tags

  resources :repbodies, :only=> %w[show index opinion destroy]

  resources :roles

  resources :users do
    resources :fileupload, :only => %w[index]
    resources :repbodies do #, :except => %w[new create destroy]
      resources :comments do
        resources :usercomments
      end
    end
  end
  resources :users#, :only => %w[indexyear] #, :except => %w[new create destroy update edit]

  resources :sessions 
  get "login" => "sessions#new", :as => "login" 
  get "logout" => "sessions#destroy", :as => "logout" 
  get "userapplicate" => "users#newext", :as => "userapplicate" 
  post "createext" => "users#createext", :as => "createext" , :via => "get"
  post "indexyear" => "users#indexyear", :as => "indexyear" , :via => "get"
  post "upload_process" => "fileupload#upload_process", :as => "upload_process" , :via => "get"
  post "repbodies" => "repbodies#index",  :via => "get"
  post "indexyeartag" => "repbodies#indexyeartag", :as => "indexyeartag", :via => "get"
  match '/acception/:id' => 'users#acception', :as => "acception", :via => "get"
  match '/mypage/:id' => 'users#mypage', :as => "mypage", :via => "get"
  match '/chpass/:id' => 'users#chpass', :as => "chpass", :via => "get"
  match '/userreportshow/:id' => 'users#userreportshow', :as => "userreportshow", :via => "get"
  match '/opinion/' => 'repbodies#opinion', :as => "opinion", :via => "get"
  match '/fileupload/' =>  'fileupload#upload', :via => "get"
  match '/years/' =>  'years#index', :via => [:get, :post]
  match '/avatar/:id' =>  'users#avatar',  :as => "avatar", :via => "get"
  match 'indexyear' => 'users#indexyear',  :via => "get"
  match 'indexyeartag' => 'repbodies#indexyeartag', :via => "get"

  match ':controller(/:action(/:id))(.:format)', :via => "get"
  root :to => 'showindex#index'
end

app/models/usercomment.rb
class Usercomment < ActiveRecord::Base
#  attr_accessible :body, :comment_id, :date, :repbody_id, :user_id
  belongs_to :repbody
  belongs_to :comment
  belongs_to :user
private
def role_params
    params.require(:usercomment).permit(:body, :comment_id, :date, :repbody_id, :user_id)
end
end

app/controllers/usercomments_controller.rb
# -*- coding: utf-8 -*-
class UsercommentsController < ApplicationController

before_filter :edit_check, :only => ['edit']

  # GET /usercomments
  # GET /usercomments.json
  def index
    @usercomments = Usercomment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @usercomments }
    end
  end

  # GET /usercomments/1
  # GET /usercomments/1.json
  def show
    @usercomment = Usercomment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @usercomment }
    end
  end

  # GET /usercomments/new
  # GET /usercomments/new.json
  def new
    @usercomment = Usercomment.new
    @repbody = Repbody.find(params[:repbody_id])
    @comment = Comment.find(params[:comment_id])
    @usercomment.repbody_id = @repbody.id
    @usercomment.comment_id = @comment.id
    @user = User.find(@repbody.user_id)
    @usercomment.user_id = current_user.id

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usercomment }

#    @repbody.commentexis = "ok"
#    @repbody.save
    end
  end

  # POST /usercomments
  # POST /usercomments.json
  def create
    @usercomment = Usercomment.new(usercomment_params)
    @comment = Comment.find(params[:comment_id])
    @repbody = Repbody.find(params[:repbody_id])
    @commentusername = User.find(@comment.user_id)
    @repbody.commentexis = "ok"
    @repbody.save
    @users = User.all
    @update = Update.new
    @current = Time.now
    @usercomment.date = @current.strftime('%Y-%m-%d %H:%M:%S')
    respond_to do |format|
      if @usercomment.save
        @update.date = @current.strftime('%Y-%m-%d %H:%M:%S')
        @update.comment = "コメント返信 For [#{@comment.user.username}]"
        @update.repbody_id = @repbody.id
#        @update.comment_id = @usercomment.id
        @update.save
        format.html { redirect_to user_repbody_path(@repbody.user_id, @repbody.id), :notice => '【メッセージ】コメントは正しく付与されました.' }
        format.json { render json: @usercomment, status: :created, location: @usercomment }
      else
        format.html { render action: "new" }
        format.json { render json: @usercomment.errors, status: :unprocessable_entity }

      end
    end
  end

  # GET /usercomments/1/edit
  def edit
    @usercomment = Usercomment.find(params[:id])
    @repbody = Repbody.find(params[:repbody_id])
    @usercomment.repbody_id = @repbody.id
    @user = User.find(@repbody.user_id)
    @usercomment.user_id = current_user.id
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # PUT /usercomments/1
  # PUT /usercomments/1.json
  def update
    @usercomment = Usercomment.find(params[:id])
    @comment = Comment.find(params[:id])
    @repbody = Repbody.find(params[:repbody_id])
    @update = Update.new
    @current = Time.now
    @usercomment.date = @current.strftime('%Y-%m-%d %H:%M:%S')
    respond_to do |format|
      if @usercomment.update_attributes(params[:usercomment])
        @update.date = @current.strftime('%Y-%m-%d %H:%M:%S')
        @update.comment = "コメント返信 For [#{@current_user.account}  -> #{@comment.user_id}]"
        @update.repbody_id = @repbody.id
        @update.save
        format.html { redirect_to mypage_path(current_user.id), :notice => '【メッセージ】コメントは正しく更新されました.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @usercomment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usercomments/1
  # DELETE /usercomments/1.json
  def destroy
    @usercomment = Usercomment.find(params[:id])
    @usercomment.destroy

    respond_to do |format|
      format.html { redirect_to usercomments_url }
      format.json { head :no_content }
    end
  end
#=begin
  private
  def edit_check
    @repbody = Repbody.find(params[:id])
#     @repbody = Repbody.find(params[:repbody_id])
#    @role = Role.find(:first, :conditions => ["position = ?", '受講生'])
    unless @repbody.user_id.to_i == current_user.id
#    if current_user.id.to_i == @repbody.user_id.to_i
       #current_user.id.to_i == @user.id.to_i
       #      repbody = Repbody.find(current_user.id)
      redirect_to mypage_path(current_user.id) , :notice => "【注意】レポート投稿者以外のコメント返信は許可されていません."
    end
  end
  #=end
  def usercomment_params
      params.require(:usercomment).permit(:usercomment, :repbody_id, :user_id, :comment_id, :body, :username, :account)
  end
end

app/helpers/usercomments_helper.rb
module UsercommentsHelper
end

app/views/usercomments/_editform.html.erb
<div id="mainbody">
  <div id="container">
    <div id="mainbox">
      <div id="mainfield">
	<!-- メインコンテンツ  -->
	<b>レポート投稿者:</b>
	<%= @user.account %>
	<table width="700px" border="0" cellspacing="1" bgcolor="#c71585">
	  <tr bgcolor="#c71585" align="left">
	    <th>
	      <p>
		<font color="#ffffff">
		  <b>Title:</b>
		  <%= @repbody.title %>
		</font>
	      </p>
	      
	    </th>
	  </tr>
	  <tr>
	    <td bgcolor="#ffffff">
	      <pre><%=raw preautolink(@repbody.body) %></pre>
	    </td>
	  </tr>
	</table>
	
	<%= form_for([current_user, @repbody, @comment, @usercomment]) do |f| %>
	<% if @usercomment.errors.any? %>
	<div id="error_explanation">
	  <h2><%= pluralize(@usercomment.errors.count, "error") %> prohibited this comment from being saved:</h2>
	  
	  <ul>
	    <% @usercomment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
	    <% end %>
	  </ul>
	</div>
	<% end %>
	<div class="field">
	  <%= f.hidden_field :user_id %><br />
	  
	</div>
	<div class="field">
	  <%= f.hidden_field :repbody_id %><br />
	</div>
	
	<div class="field">
	  <%= f.label :コメント本文 %><br />
	  <%= f.text_area :body %>
	</div>
	<div class="actions">
	  <%= f.submit %>
	</div>
	<% end %>
      </div>
    </div>
    <div id="sidebox">
      <div id="sidemenu">
	<!-- サイドメニュー  -->
	<%= render 'shared/sidemenu_public' %>
      </div>
    </div>
  </div>
</div>

app/views/usercomments/_form.html.erb
<div id="mainbody">
  <div id="container">
    <div id="mainbox">
      <div id="mainfield">
	<!-- メインコンテンツ  -->
	<b>レポート投稿者:</b>
	<%= @user.account %>
	<table width="700px" border="0" cellspacing="1" bgcolor="#c71585">
	  <tr bgcolor="#c71585" align="left">
	    <th>
	      <p>
		<font color="#ffffff">
		  <b>Title:</b>
		  <%= @repbody.title %>
		</font>
	      </p>
	      
	    </th>
	  </tr>
	  <tr>
	    <td bgcolor="#ffffff">
	      <pre><%=raw preautolink(@repbody.body) %></pre>
	    </td>
	  </tr>
	</table>
	
	<%= form_for([current_user, @repbody, @comment, @usercomment]) do |f| %>
	<% if @usercomment.errors.any? %>
	<div id="error_explanation">
	  <h2><%= pluralize(@usercomment.errors.count, "error") %> prohibited this comment from being saved:</h2>
	  
	  <ul>
	    <% @usercomment.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
	    <% end %>
	  </ul>
	</div>
	<% end %>
	<div class="field">
	  <%= f.hidden_field :user_id %><br />
	  
	</div>
	<div class="field">
	  <%= f.hidden_field :repbody_id %><br />
	</div>

	<div class="field">
	  <%= f.hidden_field :comment_id %><br />
	</div>
	
	<div class="field">
	  <%= f.label :コメント本文 %><br />
	  <%= f.text_area :body %>
	</div>
	<div class="actions">
	  <%= f.submit %>
	</div>
	<% end %>
      </div>
    </div>
    <div id="sidebox">
      <div id="sidemenu">
	<!-- サイドメニュー  -->
	<%= render 'shared/sidemenu_public' %>
      </div>
    </div>
  </div>
</div>

app/views/usercomments/edit.html.erb
<h1>コメントの更新</h1>

<%= render 'editform' %>

app/views/usercomments/index.html.erb
<h1>Listing usercomments</h1>

<table>
  <tr>
    <th>User</th>
    <th>Repbody</th>
    <th>Comment</th>
    <th>Date</th>
    <th>Body</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @usercomments.each do |usercomment| %>
  <tr>
    <td><%= usercomment.user_id %></td>
    <td><%= usercomment.repbody %></td>
    <td><%= usercomment.comment %></td>
    <td><%= usercomment.date %></td>
    <td><%= usercomment.body %></td>
    <td><%= link_to 'Show', usercomment %></td>
    <td><%= link_to 'Edit', edit_usercomment_path(usercomment) %></td>
    <td><%= link_to 'Destroy', usercomment, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Usercomment', new_usercomment_path %>

app/views/usercomments/new.html.erb
<h1>新規コメント作成</h1>


<%= render 'form' %>

app/views/usercomments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @usercomment.user_id %>
</p>

<p>
  <b>Repbody:</b>
  <%= @usercomment.repbody %>
</p>

<p>
  <b>Comment:</b>
  <%= @usercomment.comment %>
</p>

<p>
  <b>Date:</b>
  <%= @usercomment.date %>
</p>

<p>
  <b>Body:</b>
  <%= @usercomment.body %>
</p>


<%= link_to 'Edit', edit_usercomment_path(@usercomment) %> |
<%= link_to 'Back', usercomments_path %>